name: flutter_github_releases_service
description: Use github releases to update the app.
version: 0.5.0
homepage: https://github.com/januwA/flutter_github_releases_service

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  ajanuw_http: ^0.2.0
  path: ^1.6.4
  install_plugin: ^2.0.1
  permission_handler: ^5.0.0+hotfix.3
  package_info: ">=0.4.0+13 <2.0.0"
  path_provider: ^1.6.5

  flutter_downloader: ^1.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: