name: flutter_github_releases_service
description: Use github releases to update the app.
version: 0.5.1
homepage: https://github.com/januwA/flutter_github_releases_service

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  ajanuw_http: ^0.6.0
  path: ^1.8.0
  install_plugin: ^2.0.1
  permission_handler: ^6.1.0
  package_info: ^2.0.0
  path_provider: ^2.0.1

  flutter_downloader: ^1.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: